### ISSUE TITLE
Invalid arguments?

### ISSUE THREAD

**Issue by mg-developer** [ChrisGreenaway/cargo-local-registry#155]
I've downloaded last available release (0.2.0-x86_64-pc-windows-msvc.tar.gz) and I'm confused.

D:\workspace\cargo-local-registry\cargo-local-registry.exe --sync Cargo.lock D:\workspace\reg
Invalid arguments.
Usage:
    cargo local-registry [options] [<path>]

Of course, directory "D:\workspace\reg" exists.

I've also rebuild from last master (0.2.0) (linux-ubuntu) and the same effect appears. 
Can you provide me some working example of this command?

**Comment by ChrisGreenaway** [comment]
That is a valid usage of the command.

The command works fine when you run it via "cargo local-registry" rather than calling the exe directly. In other words when the command is installed with cargo install cargo-local-registry. So you if you put that binary into your C:/Users/<User>/.cargo/bin directory (or similar) you can call it using the "cargo local-registry" syntax.

Alternatively, the difference in arguments is due to the cargo wrapper adding an extra "local-registry" argument, so the apparent command line is: "cargo-local-registry local-registry --sync Cargo.lock <path>". So if you want to call the exe directly, you could add that extra "local-registry" argument in yourself.
